"use client";

import { useMemo, useState } from "react";
import { ApiError } from "@/lib/api/client";
import { createProblem } from "@/services/problemService";

const topics = ["INTRODUCTION","VARIABLES","DATA_TYPES","INPUT_OUTPUT","OPERATORS","CONDITIONALS","LOOPS","FUNCTIONS","ARRAY","STRING","MATRIX","TIME_SPACE_COMPLEXITY","RECURSION","OOP","SEARCHING","SORTING","BINARY_SEARCH","HASHING","TWO_POINTER","SLIDING_WINDOW","PREFIX_SUM","LINKED_LIST","STACK","QUEUE","DEQUE","HEAP","TREE","BINARY_SEARCH_TREE","TRIE","GREEDY","BACKTRACKING","DIVIDE_AND_CONQUER","GRAPH","DYNAMIC_PROGRAMMING","BIT_MANIPULATION","MATH"];
const patterns = ["BRUTE_FORCE","HASHING","TWO_POINTER","SLIDING_WINDOW","PREFIX_SUM","BINARY_SEARCH","SORTING","FAST_SLOW_POINTER","MONOTONIC_STACK","STACK","QUEUE","HEAP","GREEDY","RECURSION","BACKTRACKING","DIVIDE_AND_CONQUER","BIT_MANIPULATION","GRAPH_TRAVERSAL","BFS","DFS","TOPOLOGICAL_SORT","UNION_FIND","TRIE","DYNAMIC_PROGRAMMING"];
const languages = ["cpp","java","javascript","python"] as const;
const starterDefaults = { cpp: "// C++ starter code", java: "// Java starter code", javascript: "// JavaScript starter code", python: "# Python starter code" };
const tagInput = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);
const initialForm = () => ({ title: "", slug: "", problemStatement: "", topic: "", subTopics: [] as string[], tags: [] as string[], pattern: [] as string[], difficulty: "EASY" as "EASY"|"MEDIUM"|"HARD", inputFormat: "", outputFormat: "", constraints: [{ id: crypto.randomUUID(), value: "" }], examples: [{ id: crypto.randomUUID(), input: "", output: "", explanation: "" }], starterCode: { ...starterDefaults }, testCases: [{ id: crypto.randomUUID(), input: "", expectedOutput: "", isPublic: false }], supportedLanguages: [...languages], expectedTimeComplexity: "", expectedSpaceComplexity: "", companies: [] as string[], order: 1, isActive: true });

const inputClass = "mt-1 w-full rounded-inputs border border-graphite bg-abyss px-3 py-2 text-sm text-bright-gray outline-none focus:border-lavender";
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-sm text-medium-gray">{label}{children}{error && <span className="mt-1 block text-xs text-error-red">{error}</span>}</label>; }
function TagField({ label, value, onChange }: { label: string; value: string[]; onChange: (value: string[]) => void }) { return <Field label={`${label} (comma separated)`}><input className={inputClass} value={value.join(", ")} onChange={(e) => onChange(tagInput(e.target.value))} /></Field>; }

export function AddProblemForm() {
  const [form, setForm] = useState(initialForm); const [activeLanguage, setActiveLanguage] = useState<(typeof languages)[number]>("cpp"); const [errors, setErrors] = useState<Record<string,string>>({}); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(false);
  const set = <K extends keyof ReturnType<typeof initialForm>>(key: K, value: ReturnType<typeof initialForm>[K]) => setForm((current) => ({ ...current, [key]: value }));
  const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const validate = () => { const next: Record<string,string> = {}; for (const key of ["title","slug","problemStatement","topic","difficulty"] as const) if (!form[key]) next[key] = "This field is required."; for (const language of languages) if (!form.starterCode[language].trim()) next[`starterCode.${language}`] = "Starter code is required."; setErrors(next); return Object.keys(next).length === 0; };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setStatus(""); if (!validate()) return; setLoading(true); try { await createProblem({ ...form, constraints: form.constraints.map(({ value }) => value).filter(Boolean), examples: form.examples.map(({ id, ...example }) => example), testCases: form.testCases.map(({ id, ...testCase }) => testCase) }); setStatus("Problem added successfully."); setForm(initialForm()); } catch (error) { setStatus(error instanceof ApiError ? error.message : "Unable to save problem."); } finally { setLoading(false); } };
  const updateStarter = (value: string) => set("starterCode", { ...form.starterCode, [activeLanguage]: value });
  const updateRow = (key: "constraints"|"examples"|"testCases", id: string, patch: Record<string, string|boolean>) => set(key, form[key].map((row) => row.id === id ? { ...row, ...patch } : row) as never);
  const removeRow = (key: "constraints"|"examples"|"testCases", id: string) => set(key, form[key].filter((row) => row.id !== id) as never);
  const addRow = (key: "constraints"|"examples"|"testCases") => { const id = crypto.randomUUID(); if (key === "constraints") set(key, [...form.constraints, { id, value: "" }]); if (key === "examples") set(key, [...form.examples, { id, input: "", output: "", explanation: "" }]); if (key === "testCases") set(key, [...form.testCases, { id, input: "", expectedOutput: "", isPublic: false }]); };
  const selectMultiple = (key: "pattern"|"supportedLanguages", value: string) => { const current = form[key] as string[]; set(key, (current.includes(value) ? current.filter((item) => item !== value) : [...current, value]) as never); };
  const section = useMemo(() => "space-y-6 rounded-cards border border-graphite bg-surface p-5", []);
  return <form id="add-problem" onSubmit={submit} className="mx-auto max-w-[1120px] space-y-6"><div><p className="text-sm text-lavender">Content management</p><h1 className="mt-1 text-heading font-semibold text-white">Add Problem</h1><p className="mt-2 text-sm text-medium-gray">Create an active DSA problem for students.</p></div>
    <section className={section}><h2 className="text-subheading font-semibold text-white">Basic information</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Title" error={errors.title}><input required className={inputClass} value={form.title} onChange={(e) => set("title", e.target.value)} onBlur={() => !form.slug && set("slug", slugify(form.title))} /></Field><Field label="Slug" error={errors.slug}><input required className={inputClass} value={form.slug} onChange={(e) => set("slug", slugify(e.target.value))} /></Field></div><Field label="Problem statement" error={errors.problemStatement}><textarea required rows={5} className={inputClass} value={form.problemStatement} onChange={(e) => set("problemStatement", e.target.value)} /></Field></section>
    <section className={section}><h2 className="text-subheading font-semibold text-white">Classification</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Topic" error={errors.topic}><select required className={inputClass} value={form.topic} onChange={(e) => set("topic", e.target.value)}><option value="">Select topic</option>{topics.map((topic) => <option key={topic}>{topic}</option>)}</select></Field><Field label="Difficulty" error={errors.difficulty}><select className={inputClass} value={form.difficulty} onChange={(e) => set("difficulty", e.target.value as typeof form.difficulty)}><option>EASY</option><option>MEDIUM</option><option>HARD</option></select></Field></div><div className="grid gap-4 md:grid-cols-3"><TagField label="Subtopics" value={form.subTopics} onChange={(v) => set("subTopics", v)} /><TagField label="Tags" value={form.tags} onChange={(v) => set("tags", v)} /><TagField label="Companies" value={form.companies} onChange={(v) => set("companies", v)} /></div><Field label="Patterns"><div className="mt-2 flex flex-wrap gap-2">{patterns.map((pattern) => <label key={pattern} className="rounded-full border border-graphite px-2 py-1 text-xs text-muted-gray"><input type="checkbox" className="mr-1 accent-amethyst" checked={form.pattern.includes(pattern)} onChange={() => selectMultiple("pattern", pattern)} />{pattern}</label>)}</div></Field></section>
    <section className={section}><h2 className="text-subheading font-semibold text-white">Problem details</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Input format"><textarea rows={3} className={inputClass} value={form.inputFormat} onChange={(e) => set("inputFormat", e.target.value)} /></Field><Field label="Output format"><textarea rows={3} className={inputClass} value={form.outputFormat} onChange={(e) => set("outputFormat", e.target.value)} /></Field></div><div><p className="text-sm text-medium-gray">Constraints</p>{form.constraints.map((row) => <div key={row.id} className="mt-2 flex gap-2"><input className={inputClass} value={row.value} onChange={(e) => updateRow("constraints", row.id, { value: e.target.value })} /><button type="button" onClick={() => removeRow("constraints", row.id)} className="text-error-red">×</button></div>)}<button type="button" onClick={() => addRow("constraints")} className="mt-2 text-sm text-lavender">+ Add constraint</button></div><div><p className="text-sm text-medium-gray">Examples</p>{form.examples.map((row) => <div key={row.id} className="mt-3 grid gap-2 rounded-buttons border border-graphite p-3 md:grid-cols-3"><input placeholder="Input" className={inputClass} value={row.input} onChange={(e) => updateRow("examples", row.id, { input: e.target.value })} /><input placeholder="Output" className={inputClass} value={row.output} onChange={(e) => updateRow("examples", row.id, { output: e.target.value })} /><input placeholder="Explanation" className={inputClass} value={row.explanation} onChange={(e) => updateRow("examples", row.id, { explanation: e.target.value })} /><button type="button" onClick={() => removeRow("examples", row.id)} className="text-left text-xs text-error-red">Remove example</button></div>)}<button type="button" onClick={() => addRow("examples")} className="mt-2 text-sm text-lavender">+ Add example</button></div></section>
    <section className={section}><h2 className="text-subheading font-semibold text-white">Starter code</h2><div className="flex gap-2 border-b border-graphite pb-2">{languages.map((language) => <button type="button" key={language} onClick={() => setActiveLanguage(language)} className={`rounded-buttons px-3 py-2 text-sm ${activeLanguage === language ? "bg-amethyst text-white" : "text-muted-gray"}`}>{language}</button>)}</div><textarea required rows={10} className={`${inputClass} font-mono`} value={form.starterCode[activeLanguage]} onChange={(e) => updateStarter(e.target.value)} />{errors[`starterCode.${activeLanguage}`] && <p className="text-xs text-error-red">{errors[`starterCode.${activeLanguage}`]}</p>}<div className="flex flex-wrap gap-3 pt-2">{languages.map((language) => <label key={language} className="text-sm text-medium-gray"><input type="checkbox" className="mr-2 accent-amethyst" checked={form.supportedLanguages.includes(language)} onChange={() => selectMultiple("supportedLanguages", language)} />{language}</label>)}</div></section>
    <section className={section}><h2 className="text-subheading font-semibold text-white">Test cases and metadata</h2>{form.testCases.map((row) => <div key={row.id} className="grid gap-2 rounded-buttons border border-graphite p-3 md:grid-cols-3"><input placeholder="Input" className={inputClass} value={row.input} onChange={(e) => updateRow("testCases", row.id, { input: e.target.value })} /><input placeholder="Expected output" className={inputClass} value={row.expectedOutput} onChange={(e) => updateRow("testCases", row.id, { expectedOutput: e.target.value })} /><label className="flex items-center gap-2 text-sm text-medium-gray"><input type="checkbox" checked={row.isPublic} onChange={(e) => updateRow("testCases", row.id, { isPublic: e.target.checked })} />Public<button type="button" onClick={() => removeRow("testCases", row.id)} className="ml-auto text-error-red">×</button></label></div>)}<button type="button" onClick={() => addRow("testCases")} className="mt-2 text-sm text-lavender">+ Add test case</button><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="Time complexity"><input className={inputClass} value={form.expectedTimeComplexity} onChange={(e) => set("expectedTimeComplexity", e.target.value)} /></Field><Field label="Space complexity"><input className={inputClass} value={form.expectedSpaceComplexity} onChange={(e) => set("expectedSpaceComplexity", e.target.value)} /></Field><Field label="Order"><input type="number" min={1} className={inputClass} value={form.order} onChange={(e) => set("order", Number(e.target.value))} /></Field></div><label className="flex items-center gap-2 text-sm text-medium-gray"><input type="checkbox" checked={form.isActive} onChange={(e) => set("isActive", e.target.checked)} />Active</label></section>
    {status && <p role="status" className={`${status.includes("successfully") ? "text-success-green" : "text-error-red"} rounded-buttons border border-graphite bg-surface px-3 py-2 text-sm`}>{status}</p>}<button disabled={loading} className="rounded-buttons bg-amethyst px-5 py-3 text-sm font-medium text-white hover:bg-lavender hover:text-black">{loading ? "Saving..." : "Add problem"}</button>
  </form>;
}
