@baseUrl = {{$dotenv BASEURL}}

############################################################

# STUDENT AUTH APIs

############################################################

### 1. Student Signup

POST {{baseUrl}}/api/auth/student/signup
Content-Type: application/json

{
"fullname": "Abhay Patil",
"studentId": "STU001",
"email": "abhayramkrushnapatil@gmail.com",
"branch": "Computer Science and Engineering",
"college": "KBTCOE",
"collegeId": "KBT001",
"currentYear": 4,
"passingYear": 2027,
"password": "Abhay@123"
}

### 2. Student Login

POST {{baseUrl}}/api/auth/student/login
Content-Type: application/json

{
"email": "abhayramkrushnapatil@gmail.com",
"password": "Abhay@123"
}

### 3. Student Logout

POST {{baseUrl}}/api/auth/student/logout

### 4. Student Forgot Password

POST {{baseUrl}}/api/auth/student/forgot-password
Content-Type: application/json

{
"email": "abhayramkrushnapatil@gmail.com"
}

### Student - Verify OTP and Reset Password
POST {{baseUrl}}/api/auth/student/verify-otp-reset-password
Content-Type: application/json

{
    "email": "abhayramkrushnapatil@gmail.com",
    "otp": "686612",
    "password": "NewAbhay@123",
    "confirmPassword": "NewAbhay@123"
}

############################################################

# ADMIN AUTH APIs

############################################################

### 6. Admin Signup

POST {{baseUrl}}/api/auth/admin/signup
Content-Type: application/json

{
"fullname": "Placely Admin",
"email": "patilabhay484@gmail.com",
"password": "Admin@123"
}

### 7. Admin Login

POST {{baseUrl}}/api/auth/admin/login
Content-Type: application/json

{
"email": "patilabhay484@gmail.com",
"password": "Admin@123"
}

### 8. Admin Logout

POST {{baseUrl}}/api/auth/admin/logout

### 9. Admin Forgot Password

POST {{baseUrl}}/api/auth/admin/forgot-password
Content-Type: application/json

{
"email": "patilabhay484@gmail.com"
}

### Admin - Verify OTP and Reset Password
POST {{baseUrl}}/api/auth/admin/verify-otp-reset-password
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "otp": "686612",
    "password": "NewAdmin@123",
    "confirmPassword": "NewAdmin@123"
}

############################################################

# TPO AUTH APIs

############################################################

### 11. TPO Signup

POST {{baseUrl}}/api/auth/tpo/signup
Content-Type: application/json

{
"fullname": "TPO User",
"email": "patilabhay484@gmail.com",
"password": "Tpo@123"
}

### 12. TPO Login

POST {{baseUrl}}/api/auth/tpo/login
Content-Type: application/json

{
"email": "patilabhay484@gmail.com",
"password": "Tpo@123"
}

### 13. TPO Logout

POST {{baseUrl}}/api/auth/tpo/logout

### 14. TPO Forgot Password

POST {{baseUrl}}/api/auth/tpo/forgot-password
Content-Type: application/json

{
"email": "patilabhay484@gmail.com"
}

### TPO - Verify OTP and Reset Password
POST {{baseUrl}}/api/auth/tpo/verify-otp-reset-password
Content-Type: application/json

{
    "email": "tpo@gmail.com",
    "otp": "686612",
    "password": "NewTpo@123",
    "confirmPassword": "NewTpo@123"
}