
@baseUrl = {{$dotenv BASEURL}}
@StudentAccessToken = {{$dotenv STUDENT_TOKEN}}

############################################################
# LEARNING PROGRESS APIs
############################################################

### Get Complete Learning Progress
GET {{baseUrl}}/api/progress/learning
Cookie: accessToken={{StudentAccessToken}}


############################################################
# DSA PROGRESS API
############################################################

### Get DSA Progress
GET {{baseUrl}}/api/progress/DSA
Cookie: accessToken={{StudentAccessToken}}


############################################################
# SUBJECT LEARNING PROGRESS APIs
############################################################

### Get Progress of All Subjects
GET {{baseUrl}}/api/progress/subject/learning
Cookie: accessToken={{StudentAccessToken}}


############################################################
# ADD / UPDATE LEARNING PROGRESS
############################################################

### Add or Update Learning Progress
POST {{baseUrl}}/api/progress/learning
Content-Type: application/json
Cookie: accessToken={{StudentAccessToken}}

{
    "subject": "Computer Networks",
    "topicId": 1,
    "topic": "OSI Model"
}
